# Generated by Django 4.2.2 on 2023-06-09 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('stock_current', models.IntegerField(verbose_name='Estoque Atual')),
                ('stock_mini', models.PositiveIntegerField(default=0, verbose_name='Estoque mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criando em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('invoice', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota Fiscal')),
                ('movement', models.CharField(choices=[('e', 'entrada'), ('s', 'saida')], max_length=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockLineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productmodel')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stockmodel')),
            ],
        ),
    ]
