# Generated by Django 4.2.2 on 2023-06-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='stock_mini',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estoque mínimo'),
        ),
    ]
