# Generated by Django 4.2.2 on 2023-06-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productmodel_stock_mini'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_type',
            field=models.CharField(blank=True, choices=[('cx', 'caixa'), ('pcts', 'pacote'), ('grf', 'garrafa'), ('gl', 'galão'), ('cp', 'copo'), ('fltr', 'filtro'), ('bb', 'bomba'), ('sp', 'suporte')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='produtc_vol',
            field=models.CharField(blank=True, choices=[('ml', 'mililitro'), ('l', 'litro'), ('pc', 'unidade')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stock_current',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
