# Generated by Django 4.2.2 on 2023-06-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productmodel_product_type_productmodel_produtc_vol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='stocklinemodel',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='stocklinemodel',
            name='balance',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='movement',
            field=models.CharField(choices=[('e', 'entrada'), ('s', 'saida')], max_length=1, verbose_name='Movimento'),
        ),
    ]
