# Generated by Django 4.2.2 on 2023-06-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productmodel_price_alter_stocklinemodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklinemodel',
            name='amount',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
